# Generated by Django 4.2.27 on 2026-01-17 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BirdCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('common_name_ko', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(blank=True, default='', max_length=100)),
                ('short_description', models.TextField(blank=True, default='')),
                ('wikimedia_image_url', models.URLField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photo_num', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('obs_date', models.DateTimeField()),
                ('area1', models.CharField(blank=True, default='', max_length=50)),
                ('area2', models.CharField(blank=True, default='', max_length=50)),
                ('area_full', models.CharField(blank=True, default='', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('species_code', models.BigAutoField(primary_key=True, serialize=False)),
                ('common_name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('num', models.BigAutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('rec_date', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='birds.photo')),
                ('species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='birds.species')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BirdIdentifySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='identify/')),
                ('current_index', models.IntegerField(default=0)),
                ('is_finished', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selected_candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='birds.birdcandidate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identify_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='birdcandidate',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='birds.birdidentifysession'),
        ),
    ]
