# Generated by Django 4.2.27 on 2026-02-02 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='rec_date',
            new_name='reg_date',
        ),
        migrations.RemoveField(
            model_name='birdidentifysession',
            name='image',
        ),
        migrations.RemoveField(
            model_name='log',
            name='location',
        ),
        migrations.AddField(
            model_name='birdcandidate',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='birdcandidate',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='birds.species'),
        ),
        migrations.AddField(
            model_name='birdidentifysession',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='species',
            name='detail',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='species',
            name='family_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='species',
            name='order',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='species',
            name='common_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='species',
            name='scientific_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='species',
            name='species_code',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
