# Generated by Django 4.2.27 on 2026-02-23 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
